# Generated by Django 4.2.10 on 2024-07-04 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('pan_no', models.CharField(max_length=255)),
                ('total_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('in_hand_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('hra', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('deducted_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('tds', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('epf', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('net_payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
