# Generated by Django 4.2.10 on 2024-07-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_salaryformat_field_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=255)),
                ('curriculum', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('payment_type', models.CharField(max_length=255)),
                ('instalment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('no_of_instalment', models.IntegerField()),
                ('school_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('bus_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('canteen_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('miscellaneous_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('min_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('max_total_remain', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
