# Generated by Django 4.2.10 on 2024-07-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_feeformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueFeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_type', models.CharField(max_length=255)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('last_due_date', models.DateField()),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.fee')),
            ],
        ),
    ]
