# Generated by Django 4.2.10 on 2024-07-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0072_inquiryform'),
        ('management', '0006_duefeedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.studentuser'),
        ),
    ]
