# Generated by Django 4.2.10 on 2024-07-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_fee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duefeedetail',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_fee_detail', to='management.fee'),
        ),
    ]
