# Generated by Django 4.2.10 on 2024-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_duefeedetail_fee_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='leave_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='master_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_working_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
