# Generated by Django 4.2.10 on 2024-09-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_salaryformat_salary_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_month',
            field=models.IntegerField(default=1),
        ),
    ]
