# Generated by Django 4.2.10 on 2024-04-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_schoolprofilepassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('announcement_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
