# Generated by Django 4.2.10 on 2024-04-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofilepassword',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superadmin.schoolprofile'),
            preserve_default=False,
        ),
    ]
