# Generated by Django 4.2.10 on 2024-04-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_schoolprofile_password_schoolprofile_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
