# Generated by Django 4.2.10 on 2024-04-19 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0006_alter_schoolprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='principle_name',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
