# Generated by Django 4.2.10 on 2024-04-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_remove_schoolprofile_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='school_id',
        ),
    ]
