# Generated by Django 4.2.10 on 2024-04-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_remove_schoolprofile_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
