# Generated by Django 4.2.10 on 2024-04-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_alter_schoolprofile_school_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
