# Generated by Django 4.2.10 on 2024-04-19 05:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_schoolprofile_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
