# Generated by Django 4.2.10 on 2024-04-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_schoolprofile_contact_no_schoolprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
