# Generated by Django 4.2.10 on 2024-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_schoolprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
