# Generated by Django 4.2.10 on 2024-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_alter_announcement_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='role',
            field=models.CharField(default='super admin', max_length=255),
        ),
    ]
