# Generated by Django 4.2.10 on 2024-05-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_curricullumlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='curricullumlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='curricullumlist',
            name='optional_subject',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curricullumlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
