# Generated by Django 4.2.10 on 2024-06-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_remove_curricullumlist_class_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contract/'),
        ),
    ]
