# Generated by Django 4.2.10 on 2024-07-22 08:19

import EduSmart.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_remove_schoolprofile_password_schoolprofile_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='contract',
            field=models.FileField(blank=True, null=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='file'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.ImageField(blank=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
    ]
