# Generated by Django 4.2.10 on 2024-03-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rename_salary_teacheruser_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='blood_group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='religion',
            field=models.CharField(max_length=50),
        ),
    ]
