# Generated by Django 4.2.10 on 2024-03-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_teacheruser_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='add_more',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
