# Generated by Django 4.2.10 on 2024-03-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_teacheruser_add_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacheruser',
            old_name='add_more',
            new_name='class_subject_section_details',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='class_taught',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='subject',
        ),
    ]
