# Generated by Django 4.2.10 on 2024-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_rename_add_more_teacheruser_class_subject_section_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
