# Generated by Django 4.2.10 on 2024-04-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_teacheruser_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruser',
            name='certificate',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='authentication.teacheruser')),
            ],
        ),
    ]
