# Generated by Django 4.2.10 on 2024-04-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_studentuser_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='subject',
        ),
    ]
