# Generated by Django 4.2.10 on 2024-04-08 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_remove_studentuser_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='teacher',
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('management', 'Management'), ('student', 'Student'), ('teacher', 'Teacher'), ('payrollmanagement', 'PayrollManagement'), ('boarding', 'Boarding'), ('non-teaching', 'Non-teaching')], max_length=20),
        ),
    ]
