# Generated by Django 4.2.10 on 2024-04-08 12:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_certificate_teacher_certificate_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateField(auto_now_add=True, null=True)),
                ('ctc', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
