# Generated by Django 4.2.10 on 2024-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_staffuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='first_name',
            field=models.CharField(default=1, verbose_name=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffuser',
            name='last_name',
            field=models.CharField(default=1, verbose_name=255),
            preserve_default=False,
        ),
    ]
