# Generated by Django 4.2.10 on 2024-04-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_staffattendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffattendence',
            old_name='teacher',
            new_name='staff',
        ),
    ]
