# Generated by Django 4.2.10 on 2024-04-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_remove_teachersschedule_date_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersschedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacheruser'),
        ),
    ]
