# Generated by Django 4.2.10 on 2024-04-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_teacherattendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
