# Generated by Django 4.2.10 on 2024-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_user_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
