# Generated by Django 4.2.10 on 2024-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_notification_is_read_notification_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='class_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='reciver_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
