# Generated by Django 4.2.10 on 2024-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_notification_class_id_notification_reciver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('class_section', models.CharField(max_length=150)),
                ('exam_type', models.CharField(max_length=255)),
                ('exam_month', models.DateField()),
                ('more_subject', models.JSONField()),
            ],
        ),
    ]
