# Generated by Django 4.2.10 on 2024-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_timetable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
