# Generated by Django 4.2.10 on 2024-04-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_timetable_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='roll_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
