# Generated by Django 4.2.10 on 2024-04-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_studentuser_enrollment_no_studentuser_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersschedule',
            name='school_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
