# Generated by Django 4.2.10 on 2024-04-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0046_teachersschedule_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventscalender',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='eventscalender',
            name='day_event',
        ),
        migrations.RemoveField(
            model_name='eventscalender',
            name='event_date',
        ),
        migrations.AddField(
            model_name='eventscalender',
            name='is_event_calendar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventscalender',
            name='is_one_day_event',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='authentication.eventscalender')),
            ],
        ),
    ]
