# Generated by Django 4.2.10 on 2024-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_remove_eventscalender_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscalender',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventscalender',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='EventDate',
        ),
    ]
