# Generated by Django 4.2.10 on 2024-05-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0048_alter_certificate_certificate_file_and_more'),
        ('authentication', '0048_eventscalender_end_date_eventscalender_start_date_and_more'),
    ]

    operations = [
    ]
