# Generated by Django 4.2.10 on 2024-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_merge_20240501_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscalender',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
