# Generated by Django 4.2.10 on 2024-05-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0051_alter_eventscalender_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventscalender',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='eventscalender',
            name='start_time',
        ),
    ]
