# Generated by Django 4.2.10 on 2024-05-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0050_eventscalender_school_id'),
        ('authentication', '0053_eventscalender_end_time_eventscalender_start_time'),
    ]

    operations = [
    ]
