# Generated by Django 4.2.10 on 2024-05-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0054_merge_20240502_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='optional_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
