# Generated by Django 4.2.10 on 2024-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_alter_studentuser_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayreview',
            name='curriculum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
