# Generated by Django 4.2.10 on 2024-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0057_dayreview_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='curriculum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
