# Generated by Django 4.2.10 on 2024-05-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0059_classevent_classeventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.FileField(upload_to='event_image/')),
                ('class_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.eventscalender')),
            ],
        ),
    ]
