# Generated by Django 4.2.10 on 2024-05-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0060_eventimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='class_event',
            new_name='event',
        ),
    ]
