# Generated by Django 4.2.10 on 2024-05-16 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0062_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacheruser'),
        ),
    ]
