# Generated by Django 4.2.10 on 2024-05-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0063_availability_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
