# Generated by Django 4.2.10 on 2024-05-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0064_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
