# Generated by Django 4.2.10 on 2024-05-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0065_alter_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='status',
        ),
    ]
