# Generated by Django 4.2.10 on 2024-05-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_bus_school_id'),
        ('authentication', '0066_remove_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='bus_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='bus_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.route'),
        ),
    ]
