# Generated by Django 4.2.10 on 2024-06-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0067_studentuser_current_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='roll_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
