# Generated by Django 4.2.10 on 2024-06-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0068_alter_studentuser_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
