# Generated by Django 4.2.10 on 2024-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_timetable_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
