# Generated by Django 4.2.10 on 2024-07-18 11:37

from django.db import migrations, models
from EduSmart import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0072_inquiryform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='image',
            field=models.ImageField(blank=True, storage=storage_backends.AzureMediaStorage(azure_container='image'), upload_to='teacher_images/'),
        ),
    ]
