# Generated by Django 4.2.10 on 2024-07-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0075_alter_teacheruser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
