# Generated by Django 4.2.10 on 2024-07-22 05:56

import EduSmart.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0076_alter_teacheruser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='file'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='image',
            field=models.ImageField(blank=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(blank=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='image',
            field=models.ImageField(blank=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
    ]
