# Generated by Django 4.2.10 on 2024-07-24 08:24

import EduSmart.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0077_alter_certificate_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classeventimage',
            name='event_image',
            field=models.FileField(storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event_image',
            field=models.FileField(storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventscalender',
            name='event_image',
            field=models.ImageField(blank=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
    ]
