# Generated by Django 4.2.10 on 2024-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0080_alter_notification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
