# Generated by Django 4.2.10 on 2024-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0081_alter_inquiryform_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruser',
            name='fcm_token',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
