# Generated by Django 4.2.10 on 2024-04-10 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0025_teachersschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark_attendence', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentuser')),
            ],
        ),
    ]
