# Generated by Django 4.2.10 on 2024-04-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_teachersschedule'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherAttendence',
            new_name='StudentAttendence',
        ),
    ]
