# Generated by Django 4.2.10 on 2024-04-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_teacherattendence_studentattendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendence',
            old_name='teacher',
            new_name='student',
        ),
    ]
