# Generated by Django 4.2.10 on 2024-04-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_teacher_studentattendence_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExmaReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=200)),
                ('class_section', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=200)),
                ('exam_type', models.CharField(max_length=200)),
                ('exam_month', models.DateField()),
                ('marks_grades', models.JSONField()),
                ('total_marks', models.CharField(max_length=200)),
                ('overall_grades', models.CharField(max_length=200)),
                ('status', models.CharField(default=0, max_length=200)),
            ],
        ),
    ]
