# Generated by Django 4.2.10 on 2024-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_exmareportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('zoom_link', models.URLField()),
            ],
        ),
    ]
