# Generated by Django 4.2.10 on 2024-04-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_zoomlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomlink',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
