# Generated by Django 4.2.10 on 2024-04-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_zoomlink_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomlink',
            name='zoom_link',
            field=models.URLField(max_length=500),
        ),
    ]
