# Generated by Django 4.2.10 on 2024-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_zoomlink_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomlink',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
