# Generated by Django 4.2.10 on 2024-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_zoomlink_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('curriculum', models.CharField(max_length=255)),
                ('upload_link', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField()),
                ('upload_content', models.FileField(upload_to='study_material/')),
            ],
        ),
    ]
