# Generated by Django 4.2.10 on 2024-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_studentmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmaterial',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
