# Generated by Django 4.2.10 on 2024-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentmaterial_created_at_studentmaterial_school_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmaterial',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentmaterial',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmaterial',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
