# Generated by Django 4.2.10 on 2024-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentmaterial_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exmareportcard',
            name='curriculum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
