# Generated by Django 4.2.10 on 2024-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_exmareportcard_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomlink',
            name='curriculum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
