# Generated by Django 4.2.10 on 2024-05-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_connectwithteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectwithteacher',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
