# Generated by Django 4.2.10 on 2024-05-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0063_availability_teacher'),
        ('student', '0017_connectwithteacher_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectwithteacher',
            name='curriculum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectwithteacher',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacheruser'),
        ),
    ]
