# Generated by Django 4.2.10 on 2024-05-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0063_availability_teacher'),
        ('student', '0018_connectwithteacher_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectwithteacher',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.studentuser'),
        ),
    ]
