# Generated by Django 4.2.10 on 2024-05-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_connectwithteacher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectwithteacher',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
