# Generated by Django 4.2.10 on 2024-06-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_timetable_teacher'),
        ('student', '0022_studentmaterial_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exmareportcard',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.teacheruser'),
        ),
    ]
