# Generated by Django 4.2.10 on 2024-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_exmareportcard_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exmareportcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exmareportcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
