# Generated by Django 4.2.10 on 2024-07-25 13:21

import EduSmart.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_exmareportcard_created_at_exmareportcard_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaterial',
            name='upload_content',
            field=models.FileField(storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='file'), upload_to=''),
        ),
    ]
