# Generated by Django 4.2.10 on 2024-05-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_route_stop_delete_busroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
