# Generated by Django 4.2.10 on 2024-05-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_alter_studentuser_curriculum'),
        ('bus', '0004_route_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_start_from_school',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_start_timing',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='driver_gender',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='driver_phone_no',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='operator_email',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='operator_gender',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='operator_phone_no',
        ),
        migrations.AddField(
            model_name='bus',
            name='alternate_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_bus_route', to='bus.route'),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_route', to='bus.route'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_image',
            field=models.ImageField(blank=True, upload_to='buses/'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='authentication.staffuser'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='authentication.staffuser'),
        ),
    ]
