# Generated by Django 4.2.10 on 2024-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_remove_bus_bus_start_from_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
