# Generated by Django 4.2.10 on 2024-07-24 11:26

import EduSmart.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_bus_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_image',
            field=models.ImageField(blank=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
    ]
