# Generated by Django 4.2.10 on 2024-04-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_rename_subject_name_code_curriculum_subject_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='subject_code',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_name_code',
            field=models.JSONField(default=list),
        ),
    ]
