# Generated by Django 4.2.10 on 2024-04-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_curriculum_subject_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_pdf_file', models.FileField(upload_to='')),
                ('curriculum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculum')),
            ],
        ),
    ]
