# Generated by Django 4.2.10 on 2024-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_rename_subject_name_code_curriculum_optional_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='academic_session',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_name',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='optional_subject',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='primary_subject',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='select_class',
            field=models.JSONField(),
        ),
    ]
