# Generated by Django 4.2.10 on 2024-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_curriculum_academic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_name',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='optional_subject',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='primary_subject',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='select_class',
            field=models.JSONField(default=list),
        ),
    ]
