# Generated by Django 4.2.10 on 2024-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_curriculum_curriculum_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='select_class',
            field=models.CharField(max_length=255),
        ),
    ]
