# Generated by Django 4.2.10 on 2024-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_curriculum_curriculum_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
