# Generated by Django 4.2.10 on 2024-05-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_curriculum_created_at_curriculum_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='academic_session',
        ),
    ]
