# Generated by Django 4.2.10 on 2024-05-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_remove_curriculum_academic_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='optional_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_curriculum_optional_subject', to='curriculum.subjects'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='primary_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_curriculum_primary_subject', to='curriculum.subjects'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='select_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.classes'),
        ),
    ]
