# Generated by Django 4.2.10 on 2024-05-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_classes_subjects_alter_curriculum_optional_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.classes'),
        ),
    ]
