# Generated by Django 4.2.10 on 2024-05-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_subjects_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='optional_subject',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='primary_subject',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='subjects',
            name='curriculum_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculum'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='optional_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='primary_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='select_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
