# Generated by Django 4.2.10 on 2024-05-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_remove_curriculum_optional_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='curriculum_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
