# Generated by Django 4.2.10 on 2024-07-25 13:18

import EduSmart.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_curriculum_curriculum_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='syllabus',
            field=models.FileField(blank=True, null=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='file'), upload_to=''),
        ),
    ]
