# Generated by Django 4.2.10 on 2024-05-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0013_subjects_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_media', models.FileField(blank=True, null=True, upload_to='content/')),
                ('content_media_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('content_type', models.CharField(choices=[('e_book', 'E-Book'), ('e_video', 'E-Video')], max_length=10)),
                ('content_name', models.CharField(max_length=255)),
                ('content_creator', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_detail', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.curriculum')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subjects')),
            ],
        ),
    ]
