# Generated by Django 4.2.10 on 2024-05-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
