# Generated by Django 4.2.10 on 2024-05-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
