# Generated by Django 4.2.10 on 2024-07-25 12:53

import EduSmart.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=EduSmart.storage_backends.AzureMediaStorage(azure_container='image'), upload_to=''),
        ),
    ]
